---
# Loading vars
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

# Install Shorewall6 server
- name: Install the required  packages in Redhat derivatives
  yum: name={{ shorewall6_package }} state=installed
  when: ansible_os_family == 'RedHat'

- name: Install the required packages in Debian derivatives
  apt: name={{ shorewall6_package }} state=installed update_cache=yes
  when: ansible_os_family == 'Debian'

# Generate configuration
- name: Generate zones
  template: src=zones.j2 dest={{ shorewall6_zones_file }}

- name: Generate interfaces
  template: src=interfaces.j2 dest={{ shorewall6_interfaces_file }}

- name: Generate policy
  template: src=policy.j2 dest={{ shorewall6_policy_file }}

- name: Generate rules
  template: src=rules.j2 dest={{ shorewall6_rules_file }}
  
- name: Generate shorewall6.conf 
  template: src=shorewall6.conf.j2 dest={{ shorewall6_config_file }}

# Generate service configuration
- name: Generate Shorewall6 service conf
  template: src=shorewall6.j2 dest={{ shorewall6_service_config }} owner=root group=root

# Reload service
- name: Restart Shorewall6 service
  service: name={{ shorewall6_service }} state=restarted

# Enable Shorewall server
- name: Start the  Shorewall6 service
  service: name={{ shorewall6_service }} state=started enabled=yes
